/**
 * App-shell copy by locale (UI chrome only — review/draft content keeps
 * its own per-review language). Add new keys here when introducing new
 * surfaces.
 */

import type { UiLocale } from './locale';

export const appCopy = {
  ar: {
    nav: {
      reviews: 'التقييمات',
      dashboard: 'اللوحة',
      settings: 'الإعدادات',
      addReview: '+ إضافة',
      signOut: 'تسجيل الخروج',
      demoBadge: 'تجريبي',
    },
    inbox: {
      title: 'صندوق التقييمات',
      countWith: (shown: number, total: number) => `${shown} من أصل ${total} تقييم`,
      addBtn: '+ إضافة تقييم',
      anonymous: 'مجهول',
      emptyTitle: 'ما عندك تقييمات بعد.',
      emptyHint: 'أضف تقييمك الأول بالضغط على',
      emptyCta: 'إضافة تقييم',
    },
    filters: {
      urgency: 'الإلحاح',
      sentiment: 'المشاعر',
      language: 'اللغة',
      status: 'الحالة',
      clear: 'مسح الفلاتر',
      urgent: 'عاجل',
      important: 'مهم',
      normal: 'عادي',
      positive: 'إيجابي',
      neutral: 'محايد',
      negative: 'سلبي',
      arabic: 'عربي',
      english: 'English',
      mixed: 'مختلط',
      pending: 'بانتظار',
      drafted: 'بمسودة',
      responded: 'تم الرد',
    },
    detail: {
      back: '← الرجوع للصندوق',
      topicsHeading: 'الموضوعات',
      draftHeading: 'مسودة الرد',
      regenerate: '↻ اقترح صياغة أخرى',
      regenerating: 'جارٍ إنشاء صياغة...',
      newerDraft: 'الأحدث',
      olderDraft: 'الأقدم',
      draftCount: (cur: number, total: number) => `صياغة ${cur} من ${total}`,
      latestLabel: '(الأحدث)',
      copy: 'نسخ',
      copied: '✓ تم النسخ',
      save: 'حفظ التعديل',
      saving: 'جارٍ الحفظ...',
      markResponded: '✓ تم الرد',
      aiBadge: 'بمساعدة الذكاء الاصطناعي',
      noDraftYet: 'لم يتم إنشاء مسودة بعد لهذا التقييم.',
    },
    qualityCheck: {
      heading: 'تقييم جودة الرد',
      noIssues: 'لا توجد ملاحظات محددة — التقييم يعكس الدفء والتفاعل مع كلام العميل.',
    },
    dashboard: {
      title: 'لوحة المعلومات',
      summary: (name: string) => `ملخص آخر ٣٠ يوم لـ ${name}`,
      viewInbox: 'عرض الصندوق',
      stats: {
        total: 'إجمالي التقييمات',
        responseRate: 'معدل الرد',
        responseRateSub: (responded: number, total: number) => `${responded} من ${total}`,
        urgent: 'تقييمات عاجلة',
        avgSentiment: 'متوسط المشاعر',
        avgSentimentSub: 'على مقياس -٢ إلى +٢',
      },
      sentimentTitle: 'المشاعر عبر الزمن',
      sentimentSub: 'متوسط مشاعر التقييمات لكل يوم. حجم النقطة يعكس عدد التقييمات في اليوم.',
      topicsTitle: 'الموضوعات والمشاعر',
      topicsSub: 'توزيع التقييمات حسب الموضوع ومستوى المشاعر.',
      urgencyTitle: 'توزيع الإلحاح',
      urgencySub: 'كم تقييم يحتاج رداً سريعاً.',
    },
    settings: {
      title: 'إعدادات نغمة الردود',
      sub: 'التغييرات تنطبق على الردود الجديدة فقط. المسودات الموجودة تبقى كما هي.',
      back: '← الرجوع للصندوق',
      save: 'حفظ التغييرات',
      saving: 'جارٍ الحفظ...',
    },
    welcomeBanner: {
      title: 'أهلاً بك في النسخة التجريبية',
      sub: 'هذا مطعم تجريبي محمّل مسبقاً بـ ٨ تقييمات حقيقية. كل التقييمات هنا محلّلة بالذكاء الاصطناعي ولها مسودات ردود جاهزة. جرّب:',
      bullet1Prefix: '←',
      bullet1Action: 'اضغط أي تقييم',
      bullet1Suffix: 'لتشوف الرد المقترح + تقييم جودته',
      bullet2Prefix: '←',
      bullet2Action: '«اقترح صياغة أخرى»',
      bullet2Suffix: 'داخل تفاصيل التقييم',
      bullet3Prefix: '←',
      bullet3Action: 'لوحة المعلومات',
      bullet3Suffix: 'فوق — رسوم بيانات حقيقية',
      bullet2Pre: 'جرّب زر',
      bullet3Pre: 'شوف',
      dismiss: 'إخفاء',
    },
    time: {
      today: 'اليوم',
      yesterday: 'أمس',
      daysAgo: (n: number) => `قبل ${n} أيام`,
      weeksAgo: (n: number) => `قبل ${n} أسابيع`,
      monthsAgo: (n: number) => `قبل ${n} شهور`,
    },
  },
  en: {
    nav: {
      reviews: 'Reviews',
      dashboard: 'Dashboard',
      settings: 'Settings',
      addReview: '+ Add',
      signOut: 'Sign out',
      demoBadge: 'Demo',
    },
    inbox: {
      title: 'Review inbox',
      countWith: (shown: number, total: number) => `${shown} of ${total} reviews`,
      addBtn: '+ Add review',
      anonymous: 'Anonymous',
      emptyTitle: "You don't have any reviews yet.",
      emptyHint: 'Add your first review by clicking',
      emptyCta: 'Add review',
    },
    filters: {
      urgency: 'Urgency',
      sentiment: 'Sentiment',
      language: 'Language',
      status: 'Status',
      clear: 'Clear filters',
      urgent: 'Urgent',
      important: 'Important',
      normal: 'Normal',
      positive: 'Positive',
      neutral: 'Neutral',
      negative: 'Negative',
      arabic: 'العربية',
      english: 'English',
      mixed: 'Mixed',
      pending: 'Pending',
      drafted: 'Drafted',
      responded: 'Responded',
    },
    detail: {
      back: '← Back to inbox',
      topicsHeading: 'Topics',
      draftHeading: 'Reply draft',
      regenerate: '↻ Suggest another draft',
      regenerating: 'Generating...',
      newerDraft: 'Newer',
      olderDraft: 'Older',
      draftCount: (cur: number, total: number) => `Draft ${cur} of ${total}`,
      latestLabel: '(latest)',
      copy: 'Copy',
      copied: '✓ Copied',
      save: 'Save edit',
      saving: 'Saving...',
      markResponded: '✓ Mark as responded',
      aiBadge: 'AI-assisted draft',
      noDraftYet: 'No draft yet for this review.',
    },
    qualityCheck: {
      heading: 'AI quality check',
      noIssues: 'No concrete issues raised — score reflects warmth and specificity.',
    },
    dashboard: {
      title: 'Dashboard',
      summary: (name: string) => `Last 30 days for ${name}`,
      viewInbox: 'View inbox',
      stats: {
        total: 'Total reviews',
        responseRate: 'Response rate',
        responseRateSub: (responded: number, total: number) => `${responded} of ${total}`,
        urgent: 'Urgent reviews',
        avgSentiment: 'Avg. sentiment',
        avgSentimentSub: 'on a -2 to +2 scale',
      },
      sentimentTitle: 'Sentiment over time',
      sentimentSub:
        'Average sentiment per day. Point size reflects how many reviews that day.',
      topicsTitle: 'Topics and sentiment',
      topicsSub: 'Distribution of reviews by topic and sentiment level.',
      urgencyTitle: 'Urgency split',
      urgencySub: 'How many reviews need a quick response.',
    },
    settings: {
      title: 'Voice settings',
      sub: 'Changes apply only to new replies. Existing drafts stay as they are.',
      back: '← Back to inbox',
      save: 'Save changes',
      saving: 'Saving...',
    },
    welcomeBanner: {
      title: 'Welcome to the demo',
      sub: 'This is a demo restaurant pre-loaded with 8 real-feel reviews. Every review is already analyzed and has a draft reply ready. Try:',
      bullet1Prefix: '→',
      bullet1Action: 'Click any review',
      bullet1Suffix: 'to see the suggested reply + a quality grade',
      bullet2Prefix: '→',
      bullet2Action: '"Suggest another draft"',
      bullet2Suffix: 'inside any review',
      bullet3Prefix: '→',
      bullet3Action: 'Dashboard',
      bullet3Suffix: 'above — real charts on real data',
      bullet2Pre: 'Try the',
      bullet3Pre: 'Check the',
      dismiss: 'Dismiss',
    },
    time: {
      today: 'today',
      yesterday: 'yesterday',
      daysAgo: (n: number) => `${n} days ago`,
      weeksAgo: (n: number) => `${n} weeks ago`,
      monthsAgo: (n: number) => `${n} months ago`,
    },
  },
} satisfies Record<UiLocale, unknown>;

export type AppCopy = (typeof appCopy)[UiLocale];
