import Link from 'next/link';
import { getUiLocale } from '@/lib/locale';

export const metadata = {
  title: 'Privacy Policy · ReviewPilot',
  description: 'How ReviewPilot handles your data.',
};

export default async function PrivacyPage() {
  const locale = await getUiLocale();
  const ar = locale === 'ar';

  return (
    <main
      dir={ar ? 'rtl' : 'ltr'}
      lang={locale}
      className="min-h-screen bg-ink-50 text-ink-800"
    >
      <header className="mx-auto flex max-w-3xl items-center justify-between px-6 py-6">
        <Link href="/" className="text-lg font-semibold tracking-tight text-ink-900">
          ReviewPilot
        </Link>
        <Link href="/login" className="text-sm text-ink-600 hover:text-ink-900">
          {ar ? 'تسجيل الدخول' : 'Sign in'}
        </Link>
      </header>

      <article className="mx-auto max-w-3xl px-6 pb-24 prose prose-ink">
        <h1 className="text-3xl font-semibold tracking-tight text-ink-900">
          {ar ? 'سياسة الخصوصية' : 'Privacy Policy'}
        </h1>
        <p className="text-sm text-ink-500">
          {ar ? 'آخر تحديث: ٢٠٢٦-٠٥-١٩' : 'Last updated: 2026-05-19'}
        </p>

        {ar ? <BodyAr /> : <BodyEn />}
      </article>
    </main>
  );
}

function BodyEn() {
  return (
    <div className="mt-6 space-y-6 text-ink-700">
      <p>
        ReviewPilot is a portfolio project that helps Saudi restaurant owners draft
        Google review responses with AI. This page is the honest summary of what
        we collect and what we do with it.
      </p>

      <h2 className="mt-8 text-lg font-medium text-ink-900">What we store</h2>
      <ul className="list-disc ps-6 space-y-1">
        <li>Your email address (used for magic-link sign-in only)</li>
        <li>Your restaurant&apos;s name and voice profile (formality, dialect, signoff)</li>
        <li>The reviews you paste or import, and the AI-generated drafts</li>
        <li>Your edits to those drafts — they are used as few-shot examples for the next AI call</li>
        <li>Quality-grader scores generated by the meta-AI</li>
      </ul>
      <p>All of the above is stored in a Neon Postgres database in the EU.</p>

      <h2 className="mt-8 text-lg font-medium text-ink-900">Who sees your data</h2>
      <ul className="list-disc ps-6 space-y-1">
        <li>
          You and only you — your account is the only authenticated entry point.
        </li>
        <li>
          The AI provider currently configured (Groq, Google Gemini, or Anthropic
          Claude depending on the <code>AI_PROVIDER</code> setting). Reviews and drafts are sent to the provider during analysis, drafting, and grading.
          The provider&apos;s own privacy policy applies to that data flow.
        </li>
        <li>
          Resend, only when sending magic-link emails to you.
        </li>
        <li>
          Neon and Vercel, the hosting providers.
        </li>
      </ul>

      <h2 className="mt-8 text-lg font-medium text-ink-900">We do not</h2>
      <ul className="list-disc ps-6 space-y-1">
        <li>Sell or share your data with anyone other than the providers above</li>
        <li>Run third-party analytics or trackers</li>
        <li>Use your reviews to train any AI model we own (we don&apos;t train models)</li>
      </ul>

      <h2 className="mt-8 text-lg font-medium text-ink-900">Cookies</h2>
      <p>Two functional cookies, no advertising or tracking cookies:</p>
      <ul className="list-disc ps-6 space-y-1">
        <li>
          <code>better-auth.session_token</code> — keeps you signed in
        </li>
        <li>
          <code>reviewpilot_locale</code> — remembers your UI language (Arabic or English)
        </li>
      </ul>
      <p>
        Portfolio visitors who use the demo button also get a temporary{' '}
        <code>reviewpilot_demo</code> cookie that grants access to a shared demo
        restaurant. It expires after 7 days and contains only the demo user ID.
      </p>

      <h2 className="mt-8 text-lg font-medium text-ink-900">Your rights</h2>
      <ul className="list-disc ps-6 space-y-1">
        <li>
          <strong>Export</strong> — download all your data as CSV from{' '}
          <Link href="/settings" className="text-accent-dark underline">
            /settings
          </Link>
        </li>
        <li>
          <strong>Delete</strong> — wipe your account and every review/draft you
          own from the same /settings page. The delete cascades through the
          database immediately.
        </li>
        <li>
          <strong>Change email</strong> — update the email associated with your
          account from /settings.
        </li>
      </ul>

      <h2 className="mt-8 text-lg font-medium text-ink-900">Contact</h2>
      <p>
        Questions? Email{' '}
        <a href="mailto:abdulallah7981@gmail.com" className="text-accent-dark underline">
          abdulallah7981@gmail.com
        </a>
        . This is a single-developer portfolio project, so reply time varies.
      </p>
    </div>
  );
}

function BodyAr() {
  return (
    <div className="mt-6 space-y-6 text-ink-700">
      <p>
        ReviewPilot مشروع شخصي يساعد أصحاب المطاعم السعودية في صياغة ردود على
        تقييمات Google باستخدام الذكاء الاصطناعي. هذي الصفحة ملخص أمين لما نخزنه
        ووش نسوي فيه.
      </p>

      <h2 className="mt-8 text-lg font-medium text-ink-900">وش نخزّن</h2>
      <ul className="list-disc pe-6 space-y-1">
        <li>بريدك الإلكتروني (يُستخدم فقط لتسجيل الدخول عبر رابط سحري)</li>
        <li>اسم مطعمك ونغمة الردود (الرسمية، اللهجة، التوقيع)</li>
        <li>التقييمات اللي تنسخها أو تستوردها، والمسودات اللي أنشأها الذكاء الاصطناعي</li>
        <li>تعديلاتك على المسودات — تُستخدم كأمثلة قليلة للمكالمة القادمة للذكاء الاصطناعي</li>
        <li>درجات الجودة اللي يصدرها الذكاء الاصطناعي الثاني</li>
      </ul>
      <p>كل هذا يُخزن في قاعدة بيانات Neon Postgres في الاتحاد الأوروبي.</p>

      <h2 className="mt-8 text-lg font-medium text-ink-900">من يرى بياناتك</h2>
      <ul className="list-disc pe-6 space-y-1">
        <li>أنت فقط — حسابك هو المدخل الموثق الوحيد.</li>
        <li>
          مزود الذكاء الاصطناعي المُهيأ حالياً (Groq أو Google Gemini أو Anthropic
          Claude بحسب الإعداد). التقييمات والمسودات تُرسل للمزود أثناء التحليل
          والصياغة والتقييم.
        </li>
        <li>Resend، فقط لإرسال روابط تسجيل الدخول لك.</li>
        <li>Neon وVercel كمزودي الاستضافة.</li>
      </ul>

      <h2 className="mt-8 text-lg font-medium text-ink-900">ما نفعل</h2>
      <ul className="list-disc pe-6 space-y-1">
        <li>لا نبيع ولا نشارك بياناتك مع أي طرف غير المزودين أعلاه</li>
        <li>لا نستخدم أدوات تتبع أو تحليلات طرف ثالث</li>
        <li>لا نستخدم تقييماتك لتدريب أي نموذج ذكاء اصطناعي نملكه (نحن لا ندرّب نماذج)</li>
      </ul>

      <h2 className="mt-8 text-lg font-medium text-ink-900">ملفات تعريف الارتباط</h2>
      <p>كوكيز وظيفية فقط، لا تتبع ولا إعلانات:</p>
      <ul className="list-disc pe-6 space-y-1">
        <li>
          <code>better-auth.session_token</code> — يحافظ على جلستك
        </li>
        <li>
          <code>reviewpilot_locale</code> — يتذكر لغة الواجهة
        </li>
      </ul>

      <h2 className="mt-8 text-lg font-medium text-ink-900">حقوقك</h2>
      <ul className="list-disc pe-6 space-y-1">
        <li>
          <strong>التصدير</strong> — حمّل كل بياناتك بصيغة CSV من{' '}
          <Link href="/settings" className="text-accent-dark underline">
            /settings
          </Link>
        </li>
        <li>
          <strong>الحذف</strong> — احذف حسابك وكل التقييمات والمسودات من نفس الصفحة.
          الحذف يطبق فوراً ولا يمكن التراجع.
        </li>
        <li>
          <strong>تغيير البريد</strong> — حدّث البريد المرتبط بحسابك من /settings.
        </li>
      </ul>

      <h2 className="mt-8 text-lg font-medium text-ink-900">للتواصل</h2>
      <p>
        تساؤلات؟ راسل{' '}
        <a href="mailto:abdulallah7981@gmail.com" className="text-accent-dark underline">
          abdulallah7981@gmail.com
        </a>
        . المشروع فردي ومن مطور واحد، فالرد قد يتأخر.
      </p>
    </div>
  );
}
